Multi Processing (reduce the time) & check merge

make all    : not merge 
make merge :-> worked (edited)  directory location : Code_Generator/work

	modified:   build_perlmod/SRS.md
	modified:   build_perlmod/cga2class.pl
        - add sort to remove making PNG time (not random)
	modified:   build_perlmod/makePNG_jar_plantuml.sh
        - multi-processing
	modified:   copy.sh
        - add extension  .md .mdpp  (HLD.plantuml.md ,  SDD.mdpp)
